---
title: "Format des jeux de données initiaux du jeux sérieux"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("rstudioapi")
library("plyr")
library("reshape2")
library("ggplot2")


```

Importer ses données
```{r}
contr <- read.table("controls.txt")
dt_g <- read.table("Result_genos_subset-initialColl-hd.txt", header = TRUE, row.names = 1)
dt_p_ctl<- read.table("Result_phenos_controls.txt", header = TRUE)
dt_p_init<- read.table("Result_phenos_initialColl.txt", header = TRUE)
```

## Données de génotypage
```{r}
dim(dt_g)
```


## Données phénotypiques

### Control lines

```{r}
dt_p_ctl$year <- as.factor(dt_p_ctl$year)
dt_p_ctl_shape <- dcast(dt_p_ctl, ind ~ year, fun.aggregate=length, value.var="plot",fill=0, drop = F)
dt_p_ctl_shape
```


### Initial lines

```{r, echo=FALSE}
dt_p_int_count <- ddply(dt_p_init, .(ind,year), summarise, N = length(plot))
ggplot( data=dt_p_int_count , aes( y= ind, x = as.factor(year)) ) +
  geom_raster() +
  theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
```  
